!!python/object:argparse.Namespace
alpha: 20
beta: 30
content_image: images/input/brown-bear-small.jpg
drop_intermediate_images: false
img_base_name: img
learning_rate: 2.2
log_interval: 20
model: nst_vgg19
noise_ratio: 0.28
output_img_dir: images/output/
output_layer: conv4_2
pretrained_model: pretrained/imagenet-vgg-verydeep-19.mat
style_image: images/input/rudolf-bauer-sinfonie-xiii-1913-small.jpg
style_weights: [0.2, 0.2, 0.2, 0.2, 0.2]
train_steps: 200
