!!python/object:argparse.Namespace
alpha: 15
beta: 30
content_image: images/input/golden-gate-bridge-small.jpg
drop_intermediate_images: false
img_base_name: img
learning_rate: 2.5
log_interval: 20
model: nst_vgg19
noise_ratio: 0.225
output_img_dir: images/output/
output_layer: conv4_2
pretrained_model: pretrained/imagenet-vgg-verydeep-19.mat
style_image: images/input/picasso-plaster-head-and-arm-1925-small.jpg
style_weights: [0.2, 0.2, 0.2, 0.2, 0.2]
train_steps: 200
