!!python/object:argparse.Namespace
alpha: 10
beta: 25
content_image: images/input/bc-calm-small.jpg
drop_intermediate_images: false
img_base_name: img
learning_rate: 1.8
log_interval: 20
model: nst_vgg19
noise_ratio: 0.4
output_img_dir: images/output/
output_layer: conv4_2
pretrained_model: pretrained/imagenet-vgg-verydeep-19.mat
style_image: images/input/wassily-kandinsky-composition-vii-1913-small.jpg
style_weights: [0.2, 0.2, 0.2, 0.2, 0.2]
train_steps: 200
